# Manually configured integrations for local development
# Avoid default_config to bypass optional integrations such as go2rtc.

# https://www.home-assistant.io/integrations/http/
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.ha_norkko: debug
